import { useState } from "react";
import Head from "next/head";
import NavBar from "@/components/NavBar";
import {
  Chart as ChartJS,
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Colors,
} from "chart.js";
import { Doughnut, Line } from "react-chartjs-2";
import Table from "@/components/Table";

import { testData, truckData, finalData } from "./api/data.js";
import Dropdown from "@/components/Dropdown";

ChartJS.register(
  ArcElement,
  Tooltip,
  Legend,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Colors
);

const stats = [
  { name: "Resident Population", stat: "73,454" },
  { name: "Total Civilian Labor Force", stat: "36,850" },
  { name: "Unemployment Rate", stat: "4.4%" },
];

export const data = {
  labels: [
    "Nat. Resources",
    "Retail",
    "Transportation",
    "Financial Activities",
    "Prof. Services",
    "Food/Drink Services",
    "Government",
    "Health care",
    "Accomodation",
  ],
  datasets: [
    {
      label: "# Employed",
      data: [2300, 3800, 1600, 900, 2800, 4400, 4900, 2700, 4000],
      fontColor: "rgb(156 163 175)",
      backgroundColor: [
        "rgba(255, 99, 132, 0.2)",
        "rgba(54, 162, 235, 0.2)",
        "rgba(255, 206, 86, 0.2)",
        "rgba(75, 192, 192, 0.2)",
        "rgba(153, 102, 255, 0.2)",
        "rgba(255, 159, 64, 0.2)",
      ],
      borderColor: [
        "rgba(255, 99, 132, 1)",
        "rgba(54, 162, 235, 1)",
        "rgba(255, 206, 86, 1)",
        "rgba(75, 192, 192, 1)",
        "rgba(153, 102, 255, 1)",
        "rgba(255, 159, 64, 1)",
      ],
      borderWidth: 1,
    },
  ],
};

// Line Chart
const labels = ["January", "February", "March", "April", "May", "June", "July"];

export const lineData = {
  labels: ["Jun", "Jul", "Aug"],
  datasets: [
    {
      label: "Dataset 1",
      data: {
        id: 1,
        label: "",
        data: [5, 6, 7, 8, 8, 8, 8],
      },
      borderColor: "rgb(255, 99, 132)",
      backgroundColor: "rgba(255, 99, 132, 0.5)",
    },
  ],
};

export default function Home() {
  const [industry, setIndustry] = useState<keyof typeof finalData>("trucking");

  return (
    <>
      <Head>
        <title>Kauai Workforce Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gradient-to-b from-gray-900 via-gray-900 to-gray-800 min-h-screen">
        <NavBar />
        <section id="hero">
          <div
            className="container flex flex-col-reverse items-center
          px-6 mx-auto mt-10 md:flex-row"
          >
            {/* Left Item */}
            <div className="flex flex-col space-y-12 md:w/2 items-center md:items-start">
              <h1 className="text-4xl text-gray-100 font-bold text-center md:text-5xl md:text-left">
                Kauai Workforce Data Dashboard
              </h1>
              <p className="max-w-sm text-center text-gray-300 md:text-left"></p>
              <div className="border border-gray-600 w-full"></div>
            </div>
            {/* Right Item */}
          </div>
        </section>
        <section id="dashboard">
          <div className="container items-center px-6 mx-auto mt-10 ">
            <div>
              <h3 className="text-lg font-medium leading-6 text-gray-300">
                Quick facts
              </h3>
              <a
                href="https://dbedt.hawaii.gov/economic/datawarehouse/"
                className="text-sm font-medium leading-6 text-gray-500"
              >
                Source: U.S. Bureau of Labor Statistics and Hawaii State Dep. of
                Business, Economic Development <span>&#38;</span> Tourism
              </a>
              <dl className="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-3">
                {stats.map((item) => (
                  <div
                    key={item.name}
                    className="overflow-hidden rounded-lg bg-gray-800 px-4 py-5 shadow sm:p-6"
                  >
                    <dt className="truncate text-sm font-medium text-gray-400">
                      {item.name}
                    </dt>
                    <dd className="mt-1 text-3xl font-semibold tracking-tight text-gray-100">
                      {item.stat}
                    </dd>
                  </div>
                ))}
              </dl>
            </div>
            <div className="mt-20 grid grid-cols-1 items-end  gap-5 sm:grid-cols-3">
              <div className="sm:col-span-1">
                <div className="mb-5">
                  <h3 className="text-lg font-medium leading-6 text-gray-300">
                    Employment by Sector
                  </h3>
                </div>

                <div className="border-gray-200 h-96 rounded-lg bg-gray-800 px-4 py-5 sm:px-6">
                  <Doughnut
                    data={data}
                    options={{ maintainAspectRatio: false }}
                    color="rgb(156 163 175)"
                  />
                </div>
              </div>
              <div className="sm:col-span-2">
                <div className="border-gray-200 h-96 rounded-lg bg-gray-800 px-4 py-5 sm:px-6">
                  <Line
                    datasetIdKey="id"
                    data={testData}
                    options={{
                      maintainAspectRatio: false,
                      color: "rgb(156 163 175)",
                      elements: {
                        point: {
                          radius: 2,
                        },
                      },
                    }}
                  />
                </div>
              </div>
            </div>
            <div className="border border-gray-600 mt-20 w-full"></div>
            <div className="mt-20 grid grid-cols-1 gap-5 items-end sm:grid-cols-3">
              <div className="sm:col-span-1">
                <h1 className="text-2xl pb-5 text-gray-100 font-bold text-center md:text-3xl md:text-left">
                  Wages by Industry
                </h1>
                <div className="border-gray-200 h-96 rounded-lg bg-gray-800 px-4 py-5 sm:px-6">
                  <p className="max-w-sm leading-8 text-center justify-center text-gray-300 md:text-left">
                    The Quarterly Census of Employment and Wages (QCEW) is a
                    quarterly count of employment and wages released by the BLS
                    Response rates are typically high, as the primary source of
                    data is administrative data from employer Quarterly
                    Contributions Reports under the UI law for each state.
                  </p>
                  <a
                    href="https://www.bls.gov/cew/"
                    className="max-w-sm leading-8 text-center justify-center text-gray-300 md:text-left pt-10"
                  >
                    Read more
                  </a>
                </div>
              </div>
              <div className="sm:col-span-2 row-end">
                <div className="border-gray-200 h-96 rounded-lg bg-gray-800 px-4 py-5 sm:px-6">
                  <div className="place-items-end">
                    <Dropdown value={industry} onChange={setIndustry} />
                  </div>

                  <div className="h-full pb-10">
                    <Line
                      data={finalData[industry]}
                      options={{
                        plugins: {
                          title: {
                            display: true,
                            text: finalData[industry].title,
                            color: "rgb(156 163 175)",
                          },
                        },
                        maintainAspectRatio: false,
                        color: "rgb(156 163 175)",
                        elements: {
                          point: {
                            radius: 2,
                          },
                        },
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-20 pb-20 grid grid-cols-1 gap-5">
              <Table />
            </div>
          </div>
        </section>
        <footer>
          <p className="mt-10 pb-5 text-center text-xs leading-5 text-gray-500">
            &copy; 2023 Kauai Technology Group LLC, All rights reserved.
          </p>
        </footer>
      </div>
    </>
  );
}
